name: render
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libavif_api=1.3.0=h57928b3_3
  - aom=3.9.1=he0c23c2_0
  - black=26.1.0=py313haa95532_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - click=8.2.1=py313haa95532_1
  - colorama=0.4.6=py313haa95532_0
  - configparser=7.2.0=py313haa95532_0
  - dav1d=1.2.1=hcfcfb64_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=11.5.1=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - intel-openmp=2025.0.0=haa95532_1164
  - lerc=4.0.0=h6470a55_1
  - libavif16=1.3.0=ha08a409_3
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.4=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libflac=1.5.0=h08124e9_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.86.4=h0c9aed9_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblzma=5.8.2=hfd05255_0
  - libmad=0.15.1b=hcfcfb64_1001
  - libmpdec=4.0.0=hfd05255_1
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.55=h7351971_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.341.0=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libzlib=1.3.1=h2466b09_2
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - mpg123=1.32.9=h01009b0_0
  - mypy_extensions=1.0.0=py313haa95532_0
  - numpy=2.4.2=py313h22cce72_0
  - numpy-base=2.4.2=py313h1df51cf_0
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py313haa95532_1
  - pathlib=1.0.1=pyhd3eb1b0_1
  - pathspec=1.0.4=py313haa95532_0
  - pcre2=10.47=hd2b5f0e_0
  - pip=26.0.1=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=py313haa95532_0
  - portmidi=2.0.8=hac47afa_0
  - pygame=2.6.1=py313h12c88fb_0
  - pyopengl=3.1.10=pyh7428d3b_2
  - python=3.13.12=h09917c8_100_cp313
  - python_abi=3.13=8_cp313
  - pytokens=0.3.0=py313haa95532_0
  - rav1e=0.7.1=ha073cba_3
  - sdl2=2.32.56=h5112557_0
  - sdl2_image=2.8.2=h5ca362a_1
  - sdl2_mixer=2.6.3=hcd0ef4b_2
  - sdl2_ttf=2.24.0=hd2a6e60_1
  - sdl3=3.4.0=h5112557_0
  - svt-av1=4.0.0=hac47afa_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.13=h6ed50ae_3
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\User\miniconda3\envs\render
